name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: NicSouza

          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#5075CA&color_dots=#3D294C,#AB1364,#C2185B,#E91E63,#F06292
